openapi: 3.0.1
info:
  title: EatPick API
  description: API 설명
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Generated server url
security:
  - jwtAuth: []
tags:
  - name: Member
    description: Member API
paths:
  /mypage/update:
    post:
      tags:
        - Member
      description: 회원정보 수정
      operationId: myPageUpdate
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/com.example.eatpick.auth.domain.dto.request.MyPageUpdateRequest
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: >-
                  #/components/schemas/com.example.eatpick.auth.domain.dto.response.MyPageUpdateResponse
  /member/sign-up:
    post:
      tags:
        - Member
      description: 회원가입
      operationId: signUp
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/com.example.eatpick.auth.domain.dto.request.MemberRequest
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: >-
                  #/components/schemas/com.example.eatpick.auth.domain.dto.response.MemberResponse
  /member/sign-in:
    post:
      tags:
        - Member
      description: 로그인
      operationId: signIn
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/com.example.eatpick.auth.domain.dto.request.SignInRequest
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: >-
                  #/components/schemas/com.example.eatpick.auth.domain.dto.response.SignInResponse
  /member/check-password:
    post:
      tags:
        - Member
      description: 비밀번호 확인
      operationId: checkPassword
      parameters:
        - name: loginPw
          in: query
          required: true
          schema:
            type: string
        - name: verifiedLoginPw
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /member/check-nickname:
    post:
      tags:
        - Member
      description: 닉네임 중복 확인
      operationId: checkNickname
      parameters:
        - name: nickname
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /member/check-loginId:
    post:
      tags:
        - Member
      description: 아이디 중복 확인
      operationId: checkLoginId
      parameters:
        - name: loginId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /member/withdraw:
    delete:
      tags:
        - Member
      description: 회원탈퇴
      operationId: withdraw
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: >-
                  #/components/schemas/com.example.eatpick.auth.domain.dto.response.MemberResponse
components:
  schemas:
    com.example.eatpick.auth.domain.dto.request.MyPageUpdateRequest:
      type: object
      properties:
        nickname:
          type: string
        gender:
          type: string
          enum:
            - MALE
            - FEMALE
        age:
          type: integer
          format: int32
    com.example.eatpick.auth.domain.dto.response.MyPageUpdateResponse:
      type: object
      properties:
        nickname:
          type: string
        gender:
          type: string
          enum:
            - MALE
            - FEMALE
        age:
          type: integer
          format: int32
    com.example.eatpick.auth.domain.dto.request.MemberRequest:
      type: object
      properties:
        loginId:
          type: string
        loginPw:
          type: string
        verifiedLoginPw:
          type: string
        nickname:
          type: string
        gender:
          type: string
          enum:
            - MALE
            - FEMALE
        age:
          type: integer
          format: int32
        preferences:
          type: array
          items:
            type: string
            enum:
              - SPICY
              - SWEET
              - SALTY
              - SOUR
              - SAVORY
              - MILD
              - PLAIN
              - VEGAN
              - VEGETARIAN
              - SEAFOOD
              - MEAT_LOVER
              - DAIRY_FREE
              - GLUTEN_FREE
              - LOW_CARB
              - ORGANIC
              - TRADITIONAL
    com.example.eatpick.auth.domain.dto.response.MemberResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        loginId:
          type: string
        loginPw:
          type: string
        verifiedLoginPw:
          type: string
        nickname:
          type: string
        gender:
          type: string
          enum:
            - MALE
            - FEMALE
        role:
          type: string
          enum:
            - USER
            - ADMIN
        age:
          type: integer
          format: int32
        preferences:
          type: array
          items:
            type: string
            enum:
              - SPICY
              - SWEET
              - SALTY
              - SOUR
              - SAVORY
              - MILD
              - PLAIN
              - VEGAN
              - VEGETARIAN
              - SEAFOOD
              - MEAT_LOVER
              - DAIRY_FREE
              - GLUTEN_FREE
              - LOW_CARB
              - ORGANIC
              - TRADITIONAL
    com.example.eatpick.auth.domain.dto.request.SignInRequest:
      type: object
      properties:
        loginId:
          type: string
        loginPw:
          type: string
    com.example.eatpick.auth.domain.dto.response.SignInResponse:
      type: object
      properties:
        loginId:
          type: string
        loginPw:
          type: string
        grantType:
          type: string
        accessToken:
          type: string
        refreshToken:
          type: string
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
